language: ruby
bundler_args: --without development
rvm:
  - 2.2.1
before_install:
  - curl -O https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.5.1.deb && sudo dpkg -i elasticsearch-1.5.1.deb && true
  - 'echo ''index.number_of_shards: 1'' | sudo tee --append /etc/elasticsearch/elasticsearch.yml'
  - sudo service elasticsearch start
